= HalBuilder User Guide
Mark Derricutt <mark@talios.com>
2015-10-20
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]

== About HAL and HalBuilder

[quote, Mike Kelly, 'http://stateless.co/hal_specification.html[Taken from the HAL Specification]']
____
HAL is a simple way of linking with JSON or XML.

It provides a set of conventions for expressing hyperlinks to, and embeddedness of, related resources - the rest of a HAL document is just plain old JSON or XML.

HAL is a bit like HTML for machines, in that it is generic and designed to drive many different types of application. The difference is that HTML has features for presenting a graphical hypermedia interface to a ‘human actor’, whereas HAL is intended for presenting a machine hypertext interface to ‘automated actors’.
____

The HAL format, and the HalBuilder Java library provide a consistent approach to both designing
and consuming reusable, and navigable REST APIs built on the Java platform.

== Installing HalBuilder

HalBuilder is distributed via Maven Central, and the simplest way to get started is to include the `halbuilder-standard` dependency in your Maven `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>com.theoryinpractise</groupId>
    <artifactId>halbuilder-standard</artifactId>
    <version>4.0.1</version>
</dependency>
----

Or declare it in your `build.gradle` file with:

[source,groovy]
----
compile 'com.theoryinpractise:halbuilder-standard:4.0.1'
----

include::sections/gettingstarted.adoc[]

include::sections/creating.adoc[]

include::sections/consuming.adoc[]

include::sections/whyhal.adoc[]

include::sections/contributing.adoc[]
